### PR TITLE
Refactor/lib restructure

### PR DESCRIPTION
**Pull request by boyswan**

### CODE REVIEW

**Comment by Maar-io** [comment]
name `example/simple` is misleading. This is the most complex example with all crates included

**Comment by Maar-io** [comment]
Can you make it so that example imports crates it need to use. Now in example contract the rmrk crate is included which then includes all other.
Perhaps creating one more example with only minting and nesting will show the best way to do that.

**Comment by boyswan** [comment]
> Can you make it so that example imports crates it need to use. Now in example contract the rmrk crate is included which then includes all other. Perhaps creating one more example with only minting and nesting will show the best way to do that.

IMO it's better to keep to a single entry crate (much like what ink! has moved to) rather than users having to depend on crates individually. Maybe we could put crates behind features flags so users only pull in the sub-crates they need, but still only depend on the single rmrk crate?

**Comment by PierreOssun** [comment]
@boyswan agree. Let's create features with logical group of crate as you mentioned and keep a single entry crate

**Review by PierreOssun — APPROVED** [review]
LGTM

**Pull request merged**
